### ISSUE TITLE
RSS feed does not mention the username

### ISSUE THREAD

**Issue by poVoq** [imorland/syndication#5]
RSS feed does not mention the username of the person making the post.

Thanks for looking into that.

**Comment by imorland** [comment]
My understanding of the `RSS` schema is that the `<author>` tag may only contain a valid `email` address, therefore does not support `<name>` to use.

Although possible, I'd rather not expose forum users' email addresses in this way.

Ref: https://www.w3schools.com/XML/rss_tag_author.asp
